name: Merge Channel List
on: [push]
jobs:
    Merge-Channel:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: pwd
            - run: ls -al ../
            - run: ls -al $GITHUB_WORKSPACE
            - run: echo "Merging list..."
            - run: rm full_filtered.m3u
            # - run: python gen_filtered.py
            - run: echo "This job's status is ${{ job.status }}."